// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR1CYdZIkUC-diB9qze-3P8jNP3mlUWV8',
    appId: '1:794898195379:web:ed785bf2fb4f7ddade21c6',
    messagingSenderId: '794898195379',
    projectId: 'mxperts-test',
    authDomain: 'mxperts-test.firebaseapp.com',
    storageBucket: 'mxperts-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrASq8wT6MGu-of568a5EBJNpampc7PuM',
    appId: '1:794898195379:android:c59f077e9c442eedde21c6',
    messagingSenderId: '794898195379',
    projectId: 'mxperts-test',
    storageBucket: 'mxperts-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnoxoYVGflbUc1q8mzseTFPdXhzDuMqq4',
    appId: '1:794898195379:ios:458bc1d385515071de21c6',
    messagingSenderId: '794898195379',
    projectId: 'mxperts-test',
    storageBucket: 'mxperts-test.appspot.com',
    iosBundleId: 'com.example.mexpertTest',
  );
}
